import streamlit as st
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IFPNoise(object):
    def setupUi(self, IFPNoise):
        IFPNoise.setObjectName("IFPNoise")
        IFPNoise.resize(896, 494)
        IFPNoise.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IFPNoise.setWindowIcon(icon)
        IFPNoise.setDocumentMode(True)
        IFPNoise.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(IFPNoise)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 230, 481, 206))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.CalculBruit = QtWidgets.QPushButton(self.formLayoutWidget, clicked=lambda: self.Calcul_bruit())
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CalculBruit.setFont(font)
        self.CalculBruit.setObjectName("CalculBruit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.CalculBruit)
        self.EvaluationProgress1 = QtWidgets.QProgressBar(self.formLayoutWidget)
        self.EvaluationProgress1.setProperty("value", 0)
        self.EvaluationProgress1.setObjectName("EvaluationProgress1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.EvaluationProgress1)
        self.EvaluationProgress2 = QtWidgets.QProgressBar(self.formLayoutWidget)
        self.EvaluationProgress2.setProperty("value", 0)
        self.EvaluationProgress2.setObjectName("EvaluationProgress2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.EvaluationProgress2)
        self.AjoutButon = QtWidgets.QPushButton(self.formLayoutWidget,clicked=lambda: self.Ajout_proc())
        self.AjoutButon.setObjectName("AjoutButon")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.AjoutButon)
        self.CompileButon = QtWidgets.QPushButton(self.formLayoutWidget,clicked=lambda:self.Compile())
        self.CompileButon.setObjectName("CompileButon")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.CompileButon)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.Instruction = QtWidgets.QTextBrowser(self.centralwidget)
        self.Instruction.setEnabled(True)
        self.Instruction.setGeometry(QtCore.QRect(510, 230, 371, 181))
        self.Instruction.setObjectName("Instruction")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 901, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setAutoFillBackground(False)
